begin;
set local search_path = extensions, public, pg_catalog;
select plan(5);
select ok(not has_function_privilege('anon', 'public.rtc_tomtom_credentials_v1()', 'execute'), 'Anonymous callers cannot read TomTom credentials');
select ok(not has_function_privilege('authenticated', 'public.rtc_tomtom_credentials_v1()', 'execute'), 'Residents cannot directly read server credentials');
select ok(has_function_privilege('service_role', 'public.rtc_tomtom_credentials_v1()', 'execute'), 'Edge service can obtain only the provisioned TomTom credentials');
select ok((select proconfig @> array['search_path=pg_catalog'] from pg_proc where oid='public.rtc_tomtom_credentials_v1()'::regprocedure), 'Credential function has a fixed search path');
select ok(not exists(select 1 from jsonb_object_keys(public.rtc_tomtom_credentials_v1()) k where k not in ('TOMTOM_API_KEY','TOMTOM_MAPS_SDK_KEY')), 'Credential reader cannot return unrelated Vault secrets');
select * from finish();
rollback;
