android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.workers.max=1
org.gradle.parallel=false
kotlin.daemon.jvmargs=-Xmx1536m
kotlin.code.style=official
supabase.nonproduction.url=https://eqwstpdjoineycrkhpht.supabase.co
supabase.nonproduction.publishableKey=sb_publishable_Rx1MrXDBiYnszRlN5hsqmQ_vGmNN7ML

SUPABASE_URL=https://pbzzfzfgwzwdstvnwzqu.supabase.co