package za.org.rtc.community.feature.community

import android.content.Context
import java.time.Instant
import java.time.temporal.ChronoUnit
import java.util.UUID
import za.org.rtc.community.R
import za.org.rtc.community.core.CommunityComment
import za.org.rtc.community.core.CommunityPost
import za.org.rtc.community.core.MediaItem
import za.org.rtc.community.core.MediaKind
import za.org.rtc.community.core.MediaTargetType

object CommunityMockData {

    fun getSamplePosts(context: Context? = null): List<CommunityPost> {
        val now = Instant.now()
        val pkg = context?.packageName ?: "za.org.rtc.community"
        val gardenUri = "android.resource://$pkg/${R.drawable.community_park_garden}"
        val solarUri = "android.resource://$pkg/${R.drawable.community_solar_hub}"

        val gardenMedia = listOf(
            MediaItem(
                id = "mock_media_garden",
                targetType = MediaTargetType.COMMUNITY_POST,
                targetId = "mock_post_garden",
                storagePath = "community/garden.jpg",
                kind = MediaKind.IMAGE,
                mimeType = "image/jpeg",
                byteSize = 1256834L,
                position = 0,
                caption = "Community garden spring planting harvest and seedling exchange",
                signedUrl = gardenUri,
            )
        )

        val solarMedia = listOf(
            MediaItem(
                id = "mock_media_solar",
                targetType = MediaTargetType.COMMUNITY_POST,
                targetId = "mock_post_solar",
                storagePath = "community/solar.jpg",
                kind = MediaKind.IMAGE,
                mimeType = "image/jpeg",
                byteSize = 985243L,
                position = 0,
                caption = "Rooftop solar energy system powering the RTC youth tech lab",
                signedUrl = solarUri,
            )
        )

        return listOf(
            CommunityPost(
                id = "mock_post_garden",
                author = "Thandi Khumalo",
                handle = "@thandi_rtc",
                content = "🌱 Spring Harvest & Community Planting Day! We have set up 8 new organic raised garden beds today. Fresh spinach, herbs, and heirloom tomatoes are in the ground! Come visit us this Saturday at 09:00 for the community seed exchange.",
                category = "Environment & Gardening",
                createdAt = now.minus(2, ChronoUnit.HOURS).toString(),
                reactions = 24,
                comments = 3,
                viewerHasLiked = false,
                trendingScore = 92,
                isFollowedTopic = true,
                hasMedia = true,
                media = gardenMedia,
                isOfficial = false,
                authorId = "author_thandi",
            ),
            CommunityPost(
                id = "mock_post_solar",
                author = "RTC Sustainability Team",
                handle = "@rtc_green",
                content = "☀️⚡ Clean Energy Milestone: New 15kW Rooftop Solar Installation is officially live at our Community Hub! Powering the digital tech laboratory and after-school coding classrooms with 100% renewable energy.",
                category = "Infrastructure",
                createdAt = now.minus(5, ChronoUnit.HOURS).toString(),
                reactions = 42,
                comments = 2,
                viewerHasLiked = true,
                trendingScore = 88,
                isFollowedTopic = true,
                hasMedia = true,
                media = solarMedia,
                isOfficial = true,
                authorId = "author_rtc_official",
            ),
            CommunityPost(
                id = "mock_post_coding",
                author = "Sipho Ndlovu",
                handle = "@sipho_dev",
                content = "🚀 Registrations are now open for the Term 2 Youth Coding & Robotics Bootcamp! Laptops and mentors are provided free of charge for learners in Grades 8-12 every Tuesday and Thursday afternoon.",
                category = "Youth & Education",
                createdAt = now.minus(1, ChronoUnit.DAYS).toString(),
                reactions = 19,
                comments = 3,
                viewerHasLiked = false,
                trendingScore = 75,
                isFollowedTopic = false,
                hasMedia = false,
                media = emptyList(),
                isOfficial = false,
                authorId = "author_sipho",
            ),
            CommunityPost(
                id = "mock_post_cleanup",
                author = "Maria Van Zyl",
                handle = "@maria_vz",
                content = "🙌 A huge thank you to all 45 neighborhood volunteers who joined our Riverwalk Clean-Up drive yesterday! We collected over 60 bags of recyclables and restored the walking trails for the whole community.",
                category = "Community Life",
                createdAt = now.minus(2, ChronoUnit.DAYS).toString(),
                reactions = 35,
                comments = 2,
                viewerHasLiked = false,
                trendingScore = 64,
                isFollowedTopic = false,
                hasMedia = false,
                media = emptyList(),
                isOfficial = false,
                authorId = "author_maria",
            ),
            CommunityPost(
                id = "mock_post_water_update",
                author = "Municipal Works Department",
                handle = "@municipal_works",
                content = "💧 Water Supply Infrastructure Update: Emergency valve repair at Reservoir 2 is completed ahead of schedule. Water pressure is returning to normal across Wards 3, 4, and 7. Thank you for your patience while our teams worked through the night.",
                category = "Infrastructure & Utilities",
                createdAt = now.minus(3, ChronoUnit.HOURS).toString(),
                reactions = 58,
                comments = 4,
                viewerHasLiked = true,
                trendingScore = 95,
                isFollowedTopic = true,
                hasMedia = false,
                media = emptyList(),
                isOfficial = true,
                authorId = "author_municipal",
            ),
            CommunityPost(
                id = "mock_post_market",
                author = "Bongiwe Sithole",
                handle = "@bongi_crafts",
                content = "🛍️ Saturday Farmers & Artisan Market at RTC Civic Square! Over 35 local vendors with homemade preserves, organic greens, fresh sourdough, handmade leatherwork, and crafts. Live performance by the Youth Jazz Ensemble at 11:00!",
                category = "Local Business & Markets",
                createdAt = now.minus(7, ChronoUnit.HOURS).toString(),
                reactions = 47,
                comments = 3,
                viewerHasLiked = false,
                trendingScore = 84,
                isFollowedTopic = true,
                hasMedia = false,
                media = emptyList(),
                isOfficial = false,
                authorId = "author_bongi",
            ),
            CommunityPost(
                id = "mock_post_cpf_safety",
                author = "Ward 4 Community Policing Forum",
                handle = "@ward4_cpf",
                content = "🛡️ Community Safety & Neighborhood Watch Notice: Night patrol reports show an 18% drop in reported incidents following the new solar streetlights on 4th & 8th Avenue. Sector 2 meeting is this Thursday at 18:30 at the library hall.",
                category = "Public Safety",
                createdAt = now.minus(12, ChronoUnit.HOURS).toString(),
                reactions = 63,
                comments = 3,
                viewerHasLiked = true,
                trendingScore = 91,
                isFollowedTopic = true,
                hasMedia = false,
                media = emptyList(),
                isOfficial = true,
                authorId = "author_cpf",
            ),
            CommunityPost(
                id = "mock_post_library_hours",
                author = "RTC Community Library",
                handle = "@rtc_library",
                content = "📚 Extended Study & High-Speed Wi-Fi Hours: Starting this Monday, our study hall will remain open until 21:00 Monday to Thursday to support Grade 12 learners and tertiary students preparing for exams. Free printing quota included!",
                category = "Youth & Education",
                createdAt = now.minus(1, ChronoUnit.DAYS).toString(),
                reactions = 81,
                comments = 4,
                viewerHasLiked = true,
                trendingScore = 96,
                isFollowedTopic = true,
                hasMedia = false,
                media = emptyList(),
                isOfficial = true,
                authorId = "author_library",
            ),
            CommunityPost(
                id = "mock_post_sports_league",
                author = "Coach Brian Ndaba",
                handle = "@coach_brian",
                content = "⚽ Inter-Ward Junior Soccer & Netball Tournament results are out! Congratulations to West End United U-15s and Phoenix Stars Netball Club for lifting this season's trophy! Over 400 community spectators came out to cheer on our youth.",
                category = "Sports & Recreation",
                createdAt = now.minus(2, ChronoUnit.DAYS).toString(),
                reactions = 54,
                comments = 3,
                viewerHasLiked = false,
                trendingScore = 78,
                isFollowedTopic = false,
                hasMedia = false,
                media = emptyList(),
                isOfficial = false,
                authorId = "author_coach_brian",
            ),
            CommunityPost(
                id = "mock_post_tree_planting",
                author = "Green Ward Urban Forestry",
                handle = "@green_ward",
                content = "🌳 150 Indigenous Trees Planted along the Main Transit Corridor! Thanks to City Parks and 30 community volunteers for planting wild olives, white stinkwoods, and fever trees to create shaded walkways for pedestrians.",
                category = "Environment & Gardening",
                createdAt = now.minus(3, ChronoUnit.DAYS).toString(),
                reactions = 49,
                comments = 2,
                viewerHasLiked = false,
                trendingScore = 72,
                isFollowedTopic = false,
                hasMedia = false,
                media = emptyList(),
                isOfficial = false,
                authorId = "author_green_ward",
            ),
            CommunityPost(
                id = "mock_post_senior_wellness",
                author = "RTC Community Health Committee",
                handle = "@rtc_health",
                content = "🩺 Senior Citizens Wellness Wednesday: Free cardiovascular, blood sugar, and eyesight checks this Wednesday at the Community Hall from 08:30 to 12:30. Free tea and nutritional advice packets for all participants.",
                category = "Health & Wellness",
                createdAt = now.minus(4, ChronoUnit.DAYS).toString(),
                reactions = 38,
                comments = 3,
                viewerHasLiked = false,
                trendingScore = 68,
                isFollowedTopic = false,
                hasMedia = false,
                media = emptyList(),
                isOfficial = true,
                authorId = "author_health",
            ),
            CommunityPost(
                id = "mock_post_waste_recycling",
                author = "EcoCycle Resident Network",
                handle = "@ecocycle_za",
                content = "♻️ Neighborhood Recycling Update: Clear refuse bags for clean plastics, glass, and tins will be collected every Tuesday morning alongside normal refuse. Pick up extra bags at the Civic Centre reception desk free of charge.",
                category = "Civic Service",
                createdAt = now.minus(5, ChronoUnit.DAYS).toString(),
                reactions = 29,
                comments = 2,
                viewerHasLiked = false,
                trendingScore = 61,
                isFollowedTopic = false,
                hasMedia = false,
                media = emptyList(),
                isOfficial = false,
                authorId = "author_ecocycle",
            )
        )
    }

    fun getSampleComments(postId: String): List<CommunityComment> {
        val now = Instant.now()
        return when (postId) {
            "mock_post_garden" -> listOf(
                CommunityComment(
                    id = "comment_garden_1",
                    postId = postId,
                    authorId = "author_david",
                    author = "David Sithole",
                    handle = "@davids",
                    content = "Wonderful initiative! Is there rainwater irrigation available or should we bring watering cans?",
                    createdAt = now.minus(100, ChronoUnit.MINUTES).toString(),
                ),
                CommunityComment(
                    id = "comment_garden_2",
                    postId = postId,
                    authorId = "author_rtc_staff",
                    author = "RTC Coordinator",
                    handle = "@rtc_staff",
                    content = "Hi David! Yes, the 5,000L rainwater catchment tanks are fully plumbed and we have hoses ready for everyone.",
                    createdAt = now.minus(85, ChronoUnit.MINUTES).toString(),
                    isStaff = true,
                ),
                CommunityComment(
                    id = "comment_garden_3",
                    postId = postId,
                    authorId = "author_lerato",
                    author = "Lerato Mokoena",
                    handle = "@lerato_m",
                    content = "I will bring indigenous herbs and rosemary cuttings to share with the neighborhood.",
                    createdAt = now.minus(45, ChronoUnit.MINUTES).toString(),
                ),
            )
            "mock_post_solar" -> listOf(
                CommunityComment(
                    id = "comment_solar_1",
                    postId = postId,
                    authorId = "author_jason",
                    author = "Jason Adams",
                    handle = "@jason_a",
                    content = "Incredible milestone! Will there be a public energy monitor screen in the community foyer?",
                    createdAt = now.minus(4, ChronoUnit.HOURS).toString(),
                ),
                CommunityComment(
                    id = "comment_solar_2",
                    postId = postId,
                    authorId = "author_rtc_staff",
                    author = "RTC Engineering",
                    handle = "@rtc_engineering",
                    content = "Yes Jason! The live telemetry screen is installed by the reception area showing real-time kW production.",
                    createdAt = now.minus(3, ChronoUnit.HOURS).toString(),
                    isStaff = true,
                ),
            )
            "mock_post_coding" -> listOf(
                CommunityComment(
                    id = "comment_coding_1",
                    postId = postId,
                    authorId = "author_nomsa",
                    author = "Nomsa Dlamini",
                    handle = "@nomsad",
                    content = "My son attended last year's workshop and it completely sparked his interest in software engineering.",
                    createdAt = now.minus(20, ChronoUnit.HOURS).toString(),
                ),
                CommunityComment(
                    id = "comment_coding_2",
                    postId = postId,
                    authorId = "author_kevin",
                    author = "Kevin Patel",
                    handle = "@kevin_p",
                    content = "Can university computer science students volunteer as teaching assistants?",
                    createdAt = now.minus(18, ChronoUnit.HOURS).toString(),
                ),
                CommunityComment(
                    id = "comment_coding_3",
                    postId = postId,
                    authorId = "author_rtc_staff",
                    author = "RTC Youth Lead",
                    handle = "@rtc_youth",
                    content = "Absolutely Kevin! Please reach out to youth@rtc.org.za or visit the centre office.",
                    createdAt = now.minus(16, ChronoUnit.HOURS).toString(),
                    isStaff = true,
                ),
            )
            "mock_post_cleanup" -> listOf(
                CommunityComment(
                    id = "comment_cleanup_1",
                    postId = postId,
                    authorId = "author_tariq",
                    author = "Tariq Cassim",
                    handle = "@tariq_c",
                    content = "The riverbanks look so much cleaner! Let's arrange another one next month before the rains start.",
                    createdAt = now.minus(1, ChronoUnit.DAYS).toString(),
                ),
                CommunityComment(
                    id = "comment_cleanup_2",
                    postId = postId,
                    authorId = "author_maria",
                    author = "Maria Van Zyl",
                    handle = "@maria_vz",
                    content = "Agreed Tariq! We will post the next date on the Community calendar by Friday.",
                    createdAt = now.minus(22, ChronoUnit.HOURS).toString(),
                ),
            )
            "mock_post_water_update" -> listOf(
                CommunityComment(
                    id = "comment_water_1",
                    postId = postId,
                    authorId = "author_grace",
                    author = "Grace Ndlovu",
                    handle = "@grace_n",
                    content = "Pressure is already back to normal here on 5th Avenue. Thank you for the quick turnaround!",
                    createdAt = now.minus(2, ChronoUnit.HOURS).toString(),
                ),
                CommunityComment(
                    id = "comment_water_2",
                    postId = postId,
                    authorId = "author_municipal",
                    author = "Municipal Works Department",
                    handle = "@municipal_works",
                    content = "Glad to hear that Grace. If any resident notices air in the pipes, simply let the cold tap run for 30 seconds.",
                    createdAt = now.minus(90, ChronoUnit.MINUTES).toString(),
                    isStaff = true,
                ),
                CommunityComment(
                    id = "comment_water_3",
                    postId = postId,
                    authorId = "author_peter",
                    author = "Peter Botha",
                    handle = "@peter_b",
                    content = "Appreciate the team working overnight so we didn't wake up with dry taps on a Monday morning.",
                    createdAt = now.minus(45, ChronoUnit.MINUTES).toString(),
                ),
                CommunityComment(
                    id = "comment_water_4",
                    postId = postId,
                    authorId = "author_simone",
                    author = "Simone Jacobs",
                    handle = "@simone_j",
                    content = "Can confirm Ward 7 water flow is smooth and clear now too.",
                    createdAt = now.minus(20, ChronoUnit.MINUTES).toString(),
                ),
            )
            "mock_post_market" -> listOf(
                CommunityComment(
                    id = "comment_market_1",
                    postId = postId,
                    authorId = "author_anita",
                    author = "Anita Govender",
                    handle = "@anita_g",
                    content = "Are card facilities and QR code payments accepted by all stallholders?",
                    createdAt = now.minus(6, ChronoUnit.HOURS).toString(),
                ),
                CommunityComment(
                    id = "comment_market_2",
                    postId = postId,
                    authorId = "author_bongi",
                    author = "Bongiwe Sithole",
                    handle = "@bongi_crafts",
                    content = "Yes Anita! All vendors are equipped with card speedpoints and SnapScan / Zapper.",
                    createdAt = now.minus(5, ChronoUnit.HOURS).toString(),
                ),
                CommunityComment(
                    id = "comment_market_3",
                    postId = postId,
                    authorId = "author_clive",
                    author = "Clive Steyn",
                    handle = "@clive_s",
                    content = "Looking forward to hearing the youth jazz ensemble! They were fantastic at the spring festival.",
                    createdAt = now.minus(3, ChronoUnit.HOURS).toString(),
                ),
            )
            "mock_post_cpf_safety" -> listOf(
                CommunityComment(
                    id = "comment_safety_1",
                    postId = postId,
                    authorId = "author_kabelo",
                    author = "Kabelo Molefe",
                    handle = "@kabelo_m",
                    content = "The new streetlights on 8th Ave have made a huge difference for people walking home from the taxi rank.",
                    createdAt = now.minus(10, ChronoUnit.HOURS).toString(),
                ),
                CommunityComment(
                    id = "comment_safety_2",
                    postId = postId,
                    authorId = "author_cpf",
                    author = "Ward 4 CPF Team",
                    handle = "@ward4_cpf",
                    content = "Thank you Kabelo. Phase 2 of solar lighting will begin on 12th Avenue early next month.",
                    createdAt = now.minus(8, ChronoUnit.HOURS).toString(),
                    isStaff = true,
                ),
                CommunityComment(
                    id = "comment_safety_3",
                    postId = postId,
                    authorId = "author_sarah",
                    author = "Sarah Daniels",
                    handle = "@sarah_d",
                    content = "Where can residents register their CCTV cameras to assist with neighborhood coverage?",
                    createdAt = now.minus(5, ChronoUnit.HOURS).toString(),
                ),
            )
            "mock_post_library_hours" -> listOf(
                CommunityComment(
                    id = "comment_library_1",
                    postId = postId,
                    authorId = "author_ayanda",
                    author = "Ayanda Cele",
                    handle = "@ayanda_c",
                    content = "This is a lifesaver for university students during exam prep month! Thank you library staff.",
                    createdAt = now.minus(22, ChronoUnit.HOURS).toString(),
                ),
                CommunityComment(
                    id = "comment_library_2",
                    postId = postId,
                    authorId = "author_library",
                    author = "RTC Community Library",
                    handle = "@rtc_library",
                    content = "You are most welcome Ayanda! Security will be present until 21:15 each evening to ensure safe departures.",
                    createdAt = now.minus(20, ChronoUnit.HOURS).toString(),
                    isStaff = true,
                ),
                CommunityComment(
                    id = "comment_library_3",
                    postId = postId,
                    authorId = "author_marcus",
                    author = "Marcus Thorne",
                    handle = "@marcus_t",
                    content = "Is the generator connected during load reduction periods?",
                    createdAt = now.minus(18, ChronoUnit.HOURS).toString(),
                ),
                CommunityComment(
                    id = "comment_library_4",
                    postId = postId,
                    authorId = "author_library",
                    author = "RTC Community Library",
                    handle = "@rtc_library",
                    content = "Hi Marcus! The facility runs on our new solar inverter bank, so power and Wi-Fi stay on uninterrupted.",
                    createdAt = now.minus(15, ChronoUnit.HOURS).toString(),
                    isStaff = true,
                ),
            )
            "mock_post_sports_league" -> listOf(
                CommunityComment(
                    id = "comment_sports_1",
                    postId = postId,
                    authorId = "author_zola",
                    author = "Zola Mayisela",
                    handle = "@zola_m",
                    content = "What an exciting final match! The penalty shootout was pure drama.",
                    createdAt = now.minus(1, ChronoUnit.DAYS).toString(),
                ),
                CommunityComment(
                    id = "comment_sports_2",
                    postId = postId,
                    authorId = "author_thabo",
                    author = "Thabo Radebe",
                    handle = "@thabo_r",
                    content = "Well done to Coach Brian and all the organisers for keeping our youth engaged and disciplined.",
                    createdAt = now.minus(20, ChronoUnit.HOURS).toString(),
                ),
                CommunityComment(
                    id = "comment_sports_3",
                    postId = postId,
                    authorId = "author_coach_brian",
                    author = "Coach Brian Ndaba",
                    handle = "@coach_brian",
                    content = "Thank you everyone for the massive support! Summer tournament registrations open next month.",
                    createdAt = now.minus(16, ChronoUnit.HOURS).toString(),
                ),
            )
            "mock_post_tree_planting" -> listOf(
                CommunityComment(
                    id = "comment_trees_1",
                    postId = postId,
                    authorId = "author_helen",
                    author = "Helen Du Plessis",
                    handle = "@helen_dp",
                    content = "Can homeowners request a sapling for their own sidewalk verge?",
                    createdAt = now.minus(2, ChronoUnit.DAYS).toString(),
                ),
                CommunityComment(
                    id = "comment_trees_2",
                    postId = postId,
                    authorId = "author_green_ward",
                    author = "Green Ward Urban Forestry",
                    handle = "@green_ward",
                    content = "Yes Helen! Fill out the Verge Greening form on the app or visit the municipal nursery.",
                    createdAt = now.minus(1, ChronoUnit.DAYS).toString(),
                ),
            )
            "mock_post_senior_wellness" -> listOf(
                CommunityComment(
                    id = "comment_senior_1",
                    postId = postId,
                    authorId = "author_gladys",
                    author = "Gladys Sithole",
                    handle = "@gladys_s",
                    content = "My grandmother attended last month and the nursing staff were so patient and kind.",
                    createdAt = now.minus(3, ChronoUnit.DAYS).toString(),
                ),
                CommunityComment(
                    id = "comment_senior_2",
                    postId = postId,
                    authorId = "author_health",
                    author = "RTC Health Committee",
                    handle = "@rtc_health",
                    content = "Thank you Gladys. Reminder that prescription renewals for chronic medication can also be collected.",
                    createdAt = now.minus(2, ChronoUnit.DAYS).toString(),
                    isStaff = true,
                ),
                CommunityComment(
                    id = "comment_senior_3",
                    postId = postId,
                    authorId = "author_robert",
                    author = "Robert Naidoo",
                    handle = "@robert_n",
                    content = "Is wheelchair ramp access available at the side entrance?",
                    createdAt = now.minus(1, ChronoUnit.DAYS).toString(),
                ),
            )
            "mock_post_waste_recycling" -> listOf(
                CommunityComment(
                    id = "comment_waste_1",
                    postId = postId,
                    authorId = "author_leanne",
                    author = "Leanne Moodley",
                    handle = "@leanne_m",
                    content = "Where can we drop off electronic waste like old kettle cords and spent batteries?",
                    createdAt = now.minus(4, ChronoUnit.DAYS).toString(),
                ),
                CommunityComment(
                    id = "comment_waste_2",
                    postId = postId,
                    authorId = "author_ecocycle",
                    author = "EcoCycle Resident Network",
                    handle = "@ecocycle_za",
                    content = "Hi Leanne! There are dedicated e-waste bins at both the RTC Civic Centre and the Library foyer.",
                    createdAt = now.minus(3, ChronoUnit.DAYS).toString(),
                ),
            )
            else -> listOf(
                CommunityComment(
                    id = "comment_${UUID.randomUUID()}",
                    postId = postId,
                    authorId = "author_community_member",
                    author = "Community Member",
                    handle = "@community",
                    content = "Thank you for sharing this update with our neighborhood!",
                    createdAt = now.minus(30, ChronoUnit.MINUTES).toString(),
                )
            )
        }
    }
}
